/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedCommunicationsRouteImport } from './routes/_authenticated/communications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosesRouteImport } from './routes/_authenticated/diagnoses'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated/equipment'
import { Route as AuthenticatedExaminationsRouteImport } from './routes/_authenticated/examinations'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedInsuranceRouteImport } from './routes/_authenticated/insurance'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedIolRouteImport } from './routes/_authenticated/iol'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedOpticalPrescriptionsRouteImport } from './routes/_authenticated/optical-prescriptions'
import { Route as AuthenticatedOpticalShopRouteImport } from './routes/_authenticated/optical-shop'
import { Route as AuthenticatedOptometryRouteImport } from './routes/_authenticated/optometry'
import { Route as AuthenticatedOtRoomsRouteImport } from './routes/_authenticated/ot-rooms'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPharmacyRouteImport } from './routes/_authenticated/pharmacy'
import { Route as AuthenticatedPrescriptionsRouteImport } from './routes/_authenticated/prescriptions'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSurgeriesRouteImport } from './routes/_authenticated/surgeries'
import { Route as AuthenticatedInvoiceInvoiceIdRouteImport } from './routes/_authenticated/invoice.$invoiceId'
import { Route as AuthenticatedPatientPatientIdRouteImport } from './routes/_authenticated/patient.$patientId'
import { Route as AuthenticatedPurchaseOrderPoIdRouteImport } from './routes/_authenticated/purchase-order.$poId'
import { Route as AuthenticatedSurgerySurgeryIdRouteImport } from './routes/_authenticated/surgery.$surgeryId'
import { Route as AuthenticatedVisitVisitIdRouteImport } from './routes/_authenticated/visit.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationsRoute =
  AuthenticatedCommunicationsRouteImport.update({
    id: '/communications',
    path: '/communications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosesRoute = AuthenticatedDiagnosesRouteImport.update({
  id: '/diagnoses',
  path: '/diagnoses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExaminationsRoute =
  AuthenticatedExaminationsRouteImport.update({
    id: '/examinations',
    path: '/examinations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsuranceRoute = AuthenticatedInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIolRoute = AuthenticatedIolRouteImport.update({
  id: '/iol',
  path: '/iol',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpticalPrescriptionsRoute =
  AuthenticatedOpticalPrescriptionsRouteImport.update({
    id: '/optical-prescriptions',
    path: '/optical-prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpticalShopRoute =
  AuthenticatedOpticalShopRouteImport.update({
    id: '/optical-shop',
    path: '/optical-shop',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptometryRoute = AuthenticatedOptometryRouteImport.update({
  id: '/optometry',
  path: '/optometry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOtRoomsRoute = AuthenticatedOtRoomsRouteImport.update({
  id: '/ot-rooms',
  path: '/ot-rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPharmacyRoute = AuthenticatedPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescriptionsRoute =
  AuthenticatedPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSurgeriesRoute = AuthenticatedSurgeriesRouteImport.update({
  id: '/surgeries',
  path: '/surgeries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoiceInvoiceIdRoute =
  AuthenticatedInvoiceInvoiceIdRouteImport.update({
    id: '/invoice/$invoiceId',
    path: '/invoice/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientPatientIdRoute =
  AuthenticatedPatientPatientIdRouteImport.update({
    id: '/patient/$patientId',
    path: '/patient/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrderPoIdRoute =
  AuthenticatedPurchaseOrderPoIdRouteImport.update({
    id: '/purchase-order/$poId',
    path: '/purchase-order/$poId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSurgerySurgeryIdRoute =
  AuthenticatedSurgerySurgeryIdRouteImport.update({
    id: '/surgery/$surgeryId',
    path: '/surgery/$surgeryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisitVisitIdRoute =
  AuthenticatedVisitVisitIdRouteImport.update({
    id: '/visit/$visitId',
    path: '/visit/$visitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnoses': typeof AuthenticatedDiagnosesRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/examinations': typeof AuthenticatedExaminationsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/iol': typeof AuthenticatedIolRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/optical-prescriptions': typeof AuthenticatedOpticalPrescriptionsRoute
  '/optical-shop': typeof AuthenticatedOpticalShopRoute
  '/optometry': typeof AuthenticatedOptometryRoute
  '/ot-rooms': typeof AuthenticatedOtRoomsRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/surgeries': typeof AuthenticatedSurgeriesRoute
  '/invoice/$invoiceId': typeof AuthenticatedInvoiceInvoiceIdRoute
  '/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
  '/purchase-order/$poId': typeof AuthenticatedPurchaseOrderPoIdRoute
  '/surgery/$surgeryId': typeof AuthenticatedSurgerySurgeryIdRoute
  '/visit/$visitId': typeof AuthenticatedVisitVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/communications': typeof AuthenticatedCommunicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnoses': typeof AuthenticatedDiagnosesRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/examinations': typeof AuthenticatedExaminationsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/insurance': typeof AuthenticatedInsuranceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/iol': typeof AuthenticatedIolRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/optical-prescriptions': typeof AuthenticatedOpticalPrescriptionsRoute
  '/optical-shop': typeof AuthenticatedOpticalShopRoute
  '/optometry': typeof AuthenticatedOptometryRoute
  '/ot-rooms': typeof AuthenticatedOtRoomsRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pharmacy': typeof AuthenticatedPharmacyRoute
  '/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/surgeries': typeof AuthenticatedSurgeriesRoute
  '/invoice/$invoiceId': typeof AuthenticatedInvoiceInvoiceIdRoute
  '/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
  '/purchase-order/$poId': typeof AuthenticatedPurchaseOrderPoIdRoute
  '/surgery/$surgeryId': typeof AuthenticatedSurgerySurgeryIdRoute
  '/visit/$visitId': typeof AuthenticatedVisitVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/communications': typeof AuthenticatedCommunicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnoses': typeof AuthenticatedDiagnosesRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/examinations': typeof AuthenticatedExaminationsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/insurance': typeof AuthenticatedInsuranceRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/iol': typeof AuthenticatedIolRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/optical-prescriptions': typeof AuthenticatedOpticalPrescriptionsRoute
  '/_authenticated/optical-shop': typeof AuthenticatedOpticalShopRoute
  '/_authenticated/optometry': typeof AuthenticatedOptometryRoute
  '/_authenticated/ot-rooms': typeof AuthenticatedOtRoomsRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pharmacy': typeof AuthenticatedPharmacyRoute
  '/_authenticated/prescriptions': typeof AuthenticatedPrescriptionsRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/surgeries': typeof AuthenticatedSurgeriesRoute
  '/_authenticated/invoice/$invoiceId': typeof AuthenticatedInvoiceInvoiceIdRoute
  '/_authenticated/patient/$patientId': typeof AuthenticatedPatientPatientIdRoute
  '/_authenticated/purchase-order/$poId': typeof AuthenticatedPurchaseOrderPoIdRoute
  '/_authenticated/surgery/$surgeryId': typeof AuthenticatedSurgerySurgeryIdRoute
  '/_authenticated/visit/$visitId': typeof AuthenticatedVisitVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/appointments'
    | '/audit'
    | '/billing'
    | '/branches'
    | '/catalog'
    | '/communications'
    | '/dashboard'
    | '/diagnoses'
    | '/diagnostics'
    | '/equipment'
    | '/examinations'
    | '/expenses'
    | '/follow-ups'
    | '/insurance'
    | '/inventory'
    | '/iol'
    | '/leads'
    | '/optical-prescriptions'
    | '/optical-shop'
    | '/optometry'
    | '/ot-rooms'
    | '/patients'
    | '/payments'
    | '/pharmacy'
    | '/prescriptions'
    | '/procurement'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/suppliers'
    | '/surgeries'
    | '/invoice/$invoiceId'
    | '/patient/$patientId'
    | '/purchase-order/$poId'
    | '/surgery/$surgeryId'
    | '/visit/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/appointments'
    | '/audit'
    | '/billing'
    | '/branches'
    | '/catalog'
    | '/communications'
    | '/dashboard'
    | '/diagnoses'
    | '/diagnostics'
    | '/equipment'
    | '/examinations'
    | '/expenses'
    | '/follow-ups'
    | '/insurance'
    | '/inventory'
    | '/iol'
    | '/leads'
    | '/optical-prescriptions'
    | '/optical-shop'
    | '/optometry'
    | '/ot-rooms'
    | '/patients'
    | '/payments'
    | '/pharmacy'
    | '/prescriptions'
    | '/procurement'
    | '/queue'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/suppliers'
    | '/surgeries'
    | '/invoice/$invoiceId'
    | '/patient/$patientId'
    | '/purchase-order/$poId'
    | '/surgery/$surgeryId'
    | '/visit/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/appointments'
    | '/_authenticated/audit'
    | '/_authenticated/billing'
    | '/_authenticated/branches'
    | '/_authenticated/catalog'
    | '/_authenticated/communications'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnoses'
    | '/_authenticated/diagnostics'
    | '/_authenticated/equipment'
    | '/_authenticated/examinations'
    | '/_authenticated/expenses'
    | '/_authenticated/follow-ups'
    | '/_authenticated/insurance'
    | '/_authenticated/inventory'
    | '/_authenticated/iol'
    | '/_authenticated/leads'
    | '/_authenticated/optical-prescriptions'
    | '/_authenticated/optical-shop'
    | '/_authenticated/optometry'
    | '/_authenticated/ot-rooms'
    | '/_authenticated/patients'
    | '/_authenticated/payments'
    | '/_authenticated/pharmacy'
    | '/_authenticated/prescriptions'
    | '/_authenticated/procurement'
    | '/_authenticated/queue'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/suppliers'
    | '/_authenticated/surgeries'
    | '/_authenticated/invoice/$invoiceId'
    | '/_authenticated/patient/$patientId'
    | '/_authenticated/purchase-order/$poId'
    | '/_authenticated/surgery/$surgeryId'
    | '/_authenticated/visit/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communications': {
      id: '/_authenticated/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AuthenticatedCommunicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnoses': {
      id: '/_authenticated/diagnoses'
      path: '/diagnoses'
      fullPath: '/diagnoses'
      preLoaderRoute: typeof AuthenticatedDiagnosesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/examinations': {
      id: '/_authenticated/examinations'
      path: '/examinations'
      fullPath: '/examinations'
      preLoaderRoute: typeof AuthenticatedExaminationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insurance': {
      id: '/_authenticated/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AuthenticatedInsuranceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iol': {
      id: '/_authenticated/iol'
      path: '/iol'
      fullPath: '/iol'
      preLoaderRoute: typeof AuthenticatedIolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optical-prescriptions': {
      id: '/_authenticated/optical-prescriptions'
      path: '/optical-prescriptions'
      fullPath: '/optical-prescriptions'
      preLoaderRoute: typeof AuthenticatedOpticalPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optical-shop': {
      id: '/_authenticated/optical-shop'
      path: '/optical-shop'
      fullPath: '/optical-shop'
      preLoaderRoute: typeof AuthenticatedOpticalShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optometry': {
      id: '/_authenticated/optometry'
      path: '/optometry'
      fullPath: '/optometry'
      preLoaderRoute: typeof AuthenticatedOptometryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ot-rooms': {
      id: '/_authenticated/ot-rooms'
      path: '/ot-rooms'
      fullPath: '/ot-rooms'
      preLoaderRoute: typeof AuthenticatedOtRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pharmacy': {
      id: '/_authenticated/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AuthenticatedPharmacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescriptions': {
      id: '/_authenticated/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AuthenticatedPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/surgeries': {
      id: '/_authenticated/surgeries'
      path: '/surgeries'
      fullPath: '/surgeries'
      preLoaderRoute: typeof AuthenticatedSurgeriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoice/$invoiceId': {
      id: '/_authenticated/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/invoice/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoiceInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/$patientId': {
      id: '/_authenticated/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-order/$poId': {
      id: '/_authenticated/purchase-order/$poId'
      path: '/purchase-order/$poId'
      fullPath: '/purchase-order/$poId'
      preLoaderRoute: typeof AuthenticatedPurchaseOrderPoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/surgery/$surgeryId': {
      id: '/_authenticated/surgery/$surgeryId'
      path: '/surgery/$surgeryId'
      fullPath: '/surgery/$surgeryId'
      preLoaderRoute: typeof AuthenticatedSurgerySurgeryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visit/$visitId': {
      id: '/_authenticated/visit/$visitId'
      path: '/visit/$visitId'
      fullPath: '/visit/$visitId'
      preLoaderRoute: typeof AuthenticatedVisitVisitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedCommunicationsRoute: typeof AuthenticatedCommunicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosesRoute: typeof AuthenticatedDiagnosesRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedExaminationsRoute: typeof AuthenticatedExaminationsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedInsuranceRoute: typeof AuthenticatedInsuranceRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedIolRoute: typeof AuthenticatedIolRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedOpticalPrescriptionsRoute: typeof AuthenticatedOpticalPrescriptionsRoute
  AuthenticatedOpticalShopRoute: typeof AuthenticatedOpticalShopRoute
  AuthenticatedOptometryRoute: typeof AuthenticatedOptometryRoute
  AuthenticatedOtRoomsRoute: typeof AuthenticatedOtRoomsRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPharmacyRoute: typeof AuthenticatedPharmacyRoute
  AuthenticatedPrescriptionsRoute: typeof AuthenticatedPrescriptionsRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedSurgeriesRoute: typeof AuthenticatedSurgeriesRoute
  AuthenticatedInvoiceInvoiceIdRoute: typeof AuthenticatedInvoiceInvoiceIdRoute
  AuthenticatedPatientPatientIdRoute: typeof AuthenticatedPatientPatientIdRoute
  AuthenticatedPurchaseOrderPoIdRoute: typeof AuthenticatedPurchaseOrderPoIdRoute
  AuthenticatedSurgerySurgeryIdRoute: typeof AuthenticatedSurgerySurgeryIdRoute
  AuthenticatedVisitVisitIdRoute: typeof AuthenticatedVisitVisitIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedCommunicationsRoute: AuthenticatedCommunicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosesRoute: AuthenticatedDiagnosesRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedExaminationsRoute: AuthenticatedExaminationsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedInsuranceRoute: AuthenticatedInsuranceRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedIolRoute: AuthenticatedIolRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedOpticalPrescriptionsRoute:
    AuthenticatedOpticalPrescriptionsRoute,
  AuthenticatedOpticalShopRoute: AuthenticatedOpticalShopRoute,
  AuthenticatedOptometryRoute: AuthenticatedOptometryRoute,
  AuthenticatedOtRoomsRoute: AuthenticatedOtRoomsRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPharmacyRoute: AuthenticatedPharmacyRoute,
  AuthenticatedPrescriptionsRoute: AuthenticatedPrescriptionsRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedSurgeriesRoute: AuthenticatedSurgeriesRoute,
  AuthenticatedInvoiceInvoiceIdRoute: AuthenticatedInvoiceInvoiceIdRoute,
  AuthenticatedPatientPatientIdRoute: AuthenticatedPatientPatientIdRoute,
  AuthenticatedPurchaseOrderPoIdRoute: AuthenticatedPurchaseOrderPoIdRoute,
  AuthenticatedSurgerySurgeryIdRoute: AuthenticatedSurgerySurgeryIdRoute,
  AuthenticatedVisitVisitIdRoute: AuthenticatedVisitVisitIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
